theme: jekyll-theme-minimal
title: Who has the best performance in Covid-19?
description: (waiting for edit)
show_downloads: True
navigation:
  - title: Who has the best performance in Covid-19?
    url: MATH_Tian.md
